apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-auto-deployment
  namespace: kube-auto
  labels:
    type: mac
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
   #--------------------- RollingUpdate
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  #---------------------
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        runAsUser: 123
        fsGroup: 2000
      initContainers:
      - name: init-myservice
        image: busybox
        imagePullPolicy: Always
        command: ['sh', '-c', 'pwd']
        resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      containers:
      - name: nginx
        image: nginx:latest
        # gcr.io/google_containers/busybox
        imagePullPolicy: Always
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 6000; done;" ]
        env:
          - name: LBL-1
            valueFrom:
              configMapKeyRef:
                name: kube-auto-cm
                key: log.level
          - name: LBL-2
            valueFrom:
              configMapKeyRef:
                name: kube-auto-cm
                key: log.level1
          - name: LBL-3
            valueFrom:
              configMapKeyRef:
                name: kube-auto-cm
                key: log.level2
          - name: SEC_USERNAME
            valueFrom:
              secretKeyRef:
                name: kube-auto-secret
                key: username
          - name: SEC_PASSWD
            valueFrom:
              secretKeyRef:
                name: kube-auto-secret
                key: password
        resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
        volumeMounts:
        - name: mount-secrets
          mountPath: "/secrets/kubeauto"
          readOnly: true
        # livenessProbe: checks if container is alive, readiness checks if it is able to respond for requests.
        readinessProbe:
          exec:
            command:
            - cat
            - /etc/passwd
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: mount-secrets
        secret:
          secretName: kube-auto-secret


